### ISSUE TITLE
healthcheck: edge case of SSL DOWN

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#2817]
Original issue #2682

When TLS and non TLS ports are enabled in Scylla and non TLS port is not available we reports CQL SSL down.

```
├────┼────────────────┼──────────┼───────────────┼──────────────┼──────┼──────────┼──────────┼───────┼──────────────────────────────────────┤
│ UN │ DOWN SSL (0ms) │ UP (0ms) │ 52.34.185.167 │ 10072h49m5s  │ 4    │ 29.94GiB │ 2020.1.4 │ 2.3.0 │ a013a9ea-5974-4ce3-9331-1965d89521f2 │
│ UN │ DOWN SSL (0ms) │ UP (3ms) │ 52.89.223.96  │ 10072h44m1s  │ 4    │ 29.94GiB │ 2020.1.4 │ 2.3.0 │ 39ea06e3-3ea6-48ed-84b4-a27eb2555985 │
│ UN │ DOWN SSL (2ms) │ UP (5ms) │ 54.213.51.179 │ 10072h44m19s │ 4    │ 29.94GiB │ 2020.1.4 │ 2.3.0 │ 142ae628-9fb8-47fb-9b18-faf4c98b4a88 │
╰────┴────────────────┴──────────┴───────────────┴──────────────┴──────┴──────────┴──────────┴───────┴──────────────────────────────────────╯
```

Cqlsh from the Manager host

```
[centos@ip-172-31-3-116 support]$ cqlsh 52.34.185.167 9042 --cqlshrc /tmp/cqlsh.cong
Connection error: ('Unable to connect to any servers', {'52.34.185.167': AuthenticationFailed('Remote end requires authentication.',)})
[centos@ip-172-31-3-116 support]$ cqlsh --ssl 52.34.185.167 9142 --cqlshrc /tmp/cqlsh.cong
Connection error: ('Unable to conn
```

**Comment by mmatczuk** [comment]
Scylla Manager supports only one CQL port so we need to decide which one to choose or how to report both of them.
Secondly fot TLS we should report t/o in that case.

cc @adambabik

**Comment by adambabik** [comment]
I did some more research and for these clusters we have the client to node encryption available:

id | name | scylla_Version_id | cloud_provider_id | broadcast_type | cql_mode | BYOA
-- | -- | -- | -- | -- | -- | --
196 | ps_prod1 | 60 | 1 | PUBLIC | both | NO
2200 | visitor-dev | 60 | 1 | PUBLIC | encrypted | NO
2257 | visitor-prod | 60 | 1 | PUBLIC | encrypted | NO
2590 | BVCluster1 | 60 | 1 | PRIVATE | encrypted | YES

* 196: `sctool status` CQL column: `DOWN SSL`
* 2200: `sctool status` CQL column: `DOWN SSL`
* 2257: `sctool status` CQL column: `DOWN SSL`
* 2590: `sctool status` CQL column: `UP SSL`

Interestingly, `sctool` fails checking CQL status for all public clusters but it works fine for a private one. It might be a coincidence.

Using `scylla-cloud` CLI and Go CQL client:
```
[centos@ip-10-0-4-196 ~]$ sc cluster cql ping --cluster-id 196
CQL connection OK (secure=true)
[centos@ip-10-0-4-196 ~]$ sc cluster cql ping --cluster-id 2200
Error: gocql: unable to create session: unable to discover protocol version: dial tcp 3.233.115.209:9142: i/o timeout
[centos@ip-10-0-4-196 ~]$ sc cluster cql ping --cluster-id 2257
Error: gocql: unable to create session: unable to discover protocol version: dial tcp 34.200.136.87:9142: i/o timeout
[centos@ip-10-0-4-196 ~]$ sc cluster cql ping --cluster-id 2590 
CQL connection OK (secure=true)
```

Inbound rules for the admin SG:
* 196: port 9142 is there
* 2200: port 9142 is NOT there; that's why `sc cql ping` fails
* 2257: port 9142 is NOT there; that's why `sc cql ping` fails
* 2590: assuming from the output that 9142 is there

**Comment by mmatczuk** [comment]
I reproduced that locally,
