### ISSUE TITLE
[RFE] Make possible to run repair task on selected nodes only.

### ISSUE THREAD

**Issue by Pawel-Kr** [scylladb/scylla-manager#2913]
I'd like to submit a RFE making it possible to specify the node which will be repaired (and only this specified node).

Use case example:
Let's say we have a cluster with 3 nodes, RF=3, CL=QUORUM - when repair is running conventionally, latencies are spiking above our aimed limit. Having repair running on one node at time will allow 2 replicas to respond faster, which is improving efficiency.

**Comment by mmatczuk** [comment]
In this case each node has all data, and any repair would work on all the nodes.

I think the issue is the implementation of intensity setting in row-level repair - it works on all shards.
In legacy mode (you can enforce it in config file) intensity < 0 means we work on fraction of the shards giving the cluster some air.

**Comment by mmatczuk** [comment]
cc @vladzcloudius

**Comment by mmatczuk** [comment]
@ShlomiBalalis now in row-level repair setting intensity 0.5 shall run on 50% of cores at the same time.
