### ISSUE TITLE
backup: use gob instead of json for manifest storage format

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#3116]
This needs to be analyzed first but using gob can potentially reduce CPU and memory usage due to much easier parsing.
Let's take a big manifest and try to encode it in json and gob in a benchmark to see the differences.
There is also the size component gob should be smaller.

**Comment by kevinbarbour** [comment]
Did some benchmarking of JSON vs gobs for the manifests and got some interesting results. Still trying to determine what exactly causes some of the differences, but initial results are below:

## CPU and memory
With encoding and decoding of large manifests the gobs win hands down for speed, both on the encoding and decoding, but there is a significant disadvantage in memory usage and allocations when encoding gobs. Still looking into the exact cause of the large memory discrepancy.
```
BenchmarkEncodeGob-8                2394            527750 ns/op         2587312 B/op       2066 allocs/op
BenchmarkEncodeJson-8               1568            780105 ns/op             951 B/op          0 allocs/op

BenchmarkDecodeGob-8                3025            387797 ns/op         1083445 B/op      12281 allocs/op
BenchmarkDecodeJson-8                294           4118105 ns/op         2649104 B/op      10037 allocs/op
```

## Storage and size
For the size component, there is almost a 25% size decrease when using gobs vs JSON for large manifests:
```
    gob_test.go:147: gob size is 474315
    gob_test.go:153: json size is 610111
```

But when gzipped the difference becomes much less significant:
```
  gob_test.go:147: gzipped gob size is 347276 bytes
  gob_test.go:153: gzipped json size is 354979 bytes
```

## Gzip
The biggest speed up comes when you switch to gobs and cut out gzipping the encoded data. That leads to a speedup of over 10x when encoding, and 20x when decoding, for about a 30% size increase. 
```
BenchmarkEncodeGob-8                2394            527750 ns/op         2587312 B/op       2066 allocs/op
BenchmarkEncodeGobGz-8               147           7954575 ns/op         3401184 B/op       2083 allocs/op

BenchmarkEncodeJson-8               1568            780105 ns/op             951 B/op          0 allocs/op
BenchmarkEncodeJsonGz-8              136           8688756 ns/op          824848 B/op         17 allocs/op

BenchmarkDecodeGob-8                3025            387797 ns/op         1083445 B/op      12281 allocs/op
BenchmarkDecodeGobGz-8               333           3584131 ns/op         1131999 B/op      12358 allocs/op

BenchmarkDecodeJson-8                294           4118105 ns/op         2649104 B/op      10037 allocs/op
BenchmarkDecodeJsonGz-8              162           7558238 ns/op         2693680 B/op      10097 allocs/op
```

## Aside
Not as relevant, but Interestingly with smaller objects the JSON encoding is faster by a large factor, and again has the advantage in memory:
```
BenchmarkEncodeTinyGob-8         1299075               921.9 ns/op          1008 B/op         16 allocs/op
BenchmarkEncodeTinyJson-8       11922528               100.3 ns/op             0 B/op          0 allocs/op

BenchmarkDecodeTinyGob-8          123567              8984 ns/op            6640 B/op        173 allocs/op
BenchmarkDecodeTinyJson-8        1892358               625.4 ns/op           976 B/op          8 allocs/op
```

**Comment by mmatczuk** [comment]
The results are good but not great.

I had a look at how loading manifests works. All usages of loadManifestContentInto follow the same pattern:
* loadManifest
* p.forEachDir do something 

example:

```
for _, m := range manifests {
		if err := p.loadManifestContentInto(ctx, m, &c); err != nil {
			return result, errors.Wrapf(err, "load manifest (validate) %s", m.Path())
		}
		if m.Temporary {
			p.forEachDir(m, &c, tempManifestFiles.AddFiles)
		} else {
			p.forEachDir(m, &c, files.AddFiles)
		}
	}
```

I think it makes more sense to add a function that merges `loadManifestContentInto` with `forEachDir` and uses JSON stream processing.

**Comment by kevinbarbour** [comment]
I've merged the two functions with no issue, but I'm struggling on how to implement the JSON stream processing.

With the standard JSON encoding package you can stream JSON-encoded values when the root of the JSON is a list of values, but there unfortunately isn't a straightforward way to stream an array embedded in JSON object like we would need to do here. Since there is only one object at the root of the JSON document `json.Decoder.Decode()` will always decode the entire object.

The only way I can come up with to implement this would take two passes of decoding from the Reader, the first pass would decode the details into a modified version of the ManifestContent struct excluding the index containing file data (where most of the memory usage stems from). The second pass would require manually seeking to the start of the index array in the Reader and then using `json.Decoder.Decode()` in the nested array to stream the values one-by-one.

Looking around a bit still to see if there's a slightly less messy way to do this, but thinking of writing a small utility package if not that wraps the Decoder and makes seeking to a nested item and streaming values from it easier.

**Comment by mmatczuk** [comment]
Check in RcloneListDirIter for inspiration, it seems to be doing just that reading objects from an array.
