### ISSUE TITLE
repair: fix integration tests

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#3191]

**Comment by Michal-Leszczynski** [comment]
Commit 4c5ed0c8 fixed repair integration tests by changing the default repair target.
```go
func multipleUnits() repair.Target {
	return repair.Target{
		Units: []repair.Unit{
			{Keyspace: "test_repair", Tables: []string{"test_table_0"}},
			{Keyspace: "test_repair", Tables: []string{"test_table_1"}},
		},
		DC:        []string{"dc1", "dc2"},
		Continue:  true,
		Intensity: 10,
	}
}
```
The problem is that for our test setup, repairing with `Intensity: 10` and `rowLevelRepairController` always returns `false` from `shouldBlock` because of:
```go
// DENY if any host already runs at the full intensity.
// This may happen if we decrease intensity, for a while we need to reduce
// number of jobs to reduce number of busy ranges.
ranges := c.rangesForIntensity(hosts, intensity)
for _, h := range hosts {
	var (
		r  = c.busyRanges[h] + ranges
		ok bool
	)
	switch {
	case intensity == maxIntensity:
		ok = r <= c.limits[h].Max
	case intensity <= 1:
		ok = r <= c.limits[h].Default
	default:
		ok = r <= int(intensity)*c.limits[h].Default && r <= c.limits[h].Max
	}
	if !ok {
		return false
	}
}
```
and returns `true` only from:
```go
// ALLOW if nothing is running
if !c.Busy() {
	return true
}
```
This basically means that only one repair job is executed at a time, which is perhaps not that useful for testing repair procedure. Repair parallel behavior should also be tested.

On the other hand, it turns out that most of the logic standing behind repair procedure is outdated and that most of it should be refactored. Nevertheless, I reopened this issue to remind us that repair tests seem to be in a pretty poor state and we should change them and the procedure itself in the future.
