### ISSUE TITLE
Scylla Manager won't repair after startup error 

### ISSUE THREAD

**Issue by Choraden** [scylladb/scylla-manager#3212]
Scylla Manager won't repair itself, once it fails db init. 
It blocks, until database is manually truncated. 

**How to reproduce error:** 
- Start Scylla Manager 
- Kill Scylla Manager once it has started initial db migration
- Start Scylla Manager again

**the following error should occur:**
``` STARTUP ERROR: db init: apply migration "008-drop_repair_unit.cql": statement 7: Cannot add already existing table "repair_run_progress" to keyspace "scylla_manager"```

**Comment by karol-kokoszka** [comment]
Should be fixed by one of the latest commits to master https://github.com/scylladb/scylla-manager/commit/77d86a5695d767c77a764106033a817a92956d28

And I confirm that stopping (SIGTERM) scylla-manager during DB migration, before the commit above was included, caused scylla-manager to not start again without truncating the db.

@Choraden 
Did you check it with latest master ?
