### ISSUE TITLE
Run all CLI commands in manager slice

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3259]
We should run all scylla-manager-agent CLI commands in manager slice, so we ensure that all the limits are derived from scylla-manager-agent service.
To do so, CLI should act as a proxy between shell and http server responsible for taking the apropriate action.

HTTP server must listen on "127.0.0.1" to allow connections from localhost only.

Scylla-manager-agent commands are defined in `pkg/cmd/agent`

It addresses https://github.com/scylladb/scylla-manager/issues/3190

**Comment by Michal-Leszczynski** [comment]
Unfortunately, I think that this approach won't work.
Current implementation of our rclone fork does not allow to use any config except for the global one set in rclone package variable. It can be seen in this fragment of code:
```go
// AddConfig returns a mutable config structure based on a shallow
// copy of that found in ctx and returns a new context with that added
// to it.
func AddConfig(ctx context.Context) (context.Context, *ConfigInfo) {
	panic("changing config")
}
```
Even if we brought back this function (which was deleted by the original maintainer for a probably good reason) that would allow us to create and modify new config for `download-files/benchmark` commands and pass it to rclone functions via context, there is still a problem with things like setting rate limit. In order to do that, current implementation of `download-files/benchmark` modifies another global variable from rclone pkg `TokenBucket`, that is also used by agent's rclone server. In this case, we cannot pass `TokenBucket` via context, so I don't see any reasonable solution to this problem (not to mention that I'm not sure if passing config via context would even work here). 

Since agent's rclone server and the new server mentioned in this issue would be created by the same code, they would share rclone package global variables (config, TokenBucket) and since both of those servers would like to initialize them to some specific, possibly different values, this could cause a lot of issues in the future.

Currently `scylla-manager-agent download-files/benchmark` commands are run with separate rclone packages, which solves this problem, but creates issue with inheriting limits from agent's slice. Maybe the best solution is to mention it in documentation and require users to run this command via something like:
`sudo systemd-run --slice scylla-helper.slice ./scylla-manager-agent download-files`
but I have yet to test if something like this even works.

**Comment by mykaul** [comment]
@Michal-Leszczynski - what's the next step here?

**Comment by karol-kokoszka** [comment]
@mykaul There is a workaround for that. As it looks tricky to run every single command of scylla-manager-agent in manager slice (do to the limitations coming from the RClone server we keep under the hood of manager), it's still an option to just set the limits in the current bash session which will execute the cmd.
In terms of `download-files`, it's just
```
ulimit -n {expected-value}     // set the max number of open file descriptors
scylla-manager-agent download-files
```
The only thing we must do is to update the manager documentation.

**Comment by mykaul** [comment]
> @mykaul There is a workaround for that. As it looks tricky to run every single command of scylla-manager-agent in manager slice (do to the limitations coming from the RClone server we keep under the hood of manager), it's still an option to just set the limits in the current bash session which will execute the cmd. In terms of `download-files`, it's just
> 
> ```
> ulimit -n {expected-value}     // set the max number of open file descriptors
> scylla-manager-agent download-files
> ```
> 
> The only thing we must do is to update the manager documentation.

Unsure I completely understood - do we expect users to do this? When? To which value would we change the ulimit? How would they know?

**Comment by karol-kokoszka** [comment]
This issue was created out of the long conversation we had in #3190 
Our field engineering reported to us that when tried to use the `download-files` cmd on scylla-manager-agent, the process reached the moment when it complained about exhausted limit of available file descriptors.
The initial though was, that all the agent command are executed within single process (some HTTP server handling them) and we have some leaks of the descriptors as the limit set on agent service was quite big and more than enough.
But this is not true.
Seems that couple of manager-agent commands were written the way that they are working separately, so they take the limits from the parent process (bash session).
Now, after @Michal-Leszczynski checks we see that it was done due to the limitations of RClone server.
`download-files` for example changes the configuration of RClone. But changing config of RClone on agent-server is not possible as the change would affect the complete behaviour of agent server.
So, `download-files` is not going through any server, but it start's a new one just for this command purpose.
RClone is something what we use to transfer files between different storages (s3, gcs, local).

> Unsure I completely understood - do we expect users to do this? When? To which value would we change the ulimit? How would they know?

Yes, we expect users to do it.
If you ask about the expected value that should be set. We must provide in the documentation what is the expected max limit. It's actually number of tables kept in the DB * concurrency set with the cmd flag.
Default limit for `file-descriptors` is 1024. Default concurrency is `number of cores` * 2.
Assuming that DB has 200 tables and agent is working on 8 cores machine = 200 * 8 * 2 = 1600.
So the limit can be reached already.

So, I feel it's enough to include these limitation to the documentation and suggest to execute `ulimit -n 50000` before executing cmd itself (or higher value if they want to increase the concurrency).

This command tough - `download-files` is not something with what customers (or field engineering) is/will deal often.

**Comment by mykaul** [comment]
```ulimit -n 50000``` sounds good to me as a documentation item, as opposed to something less concrete.

I wonder if newer rclone releases deal with it though.
