### ISSUE TITLE
Upgrade to newer rclone version

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-manager#3291]
Looking @ https://rclone.org/changelog/#v1-61-1-2022-12-23 , there's quite a lot of work that got into rclone, and specifically S3 backend, worth evaluating if we should move to a newer version.

**Comment by karol-kokoszka** [comment]
@mykaul This is definitely something what we should do in scylla-manager.
It will be tricky task tough. We are using internal ScyllaDB fork of RClone repository that is amended a little bit to meet the requirements that original creators of scylla-manager had. Here is the fork https://github.com/scylladb/rclone

According to github, we are 1742 commits behind RClone master.

Only person who participated in the original development of scylla-manager and is still with us is @zimnx .
We need to find the reason of why we use fork and what scylla specific changes are introduced here to not overwrite them with anything what may come from the original repo.

Frankly speaking this choice of keeping fork instead of contributing to original repo creates additional complexity to us. 
Original repo is well maintained, has active community with many opened discussions + new features are constantly being added.
We don't have resources to do the same with our fork.

Maybe, just maybe we should consider and check how difficult it is to completly replace fork with the original repo even if it leads to the situation where scylla-manager have to be redesigned a bit due to the differences between fork and original repo.

Let me bring this issue to the manager planning doc.

**Comment by zimnx** [comment]
AFAIR we used a fork just because we needed to release, and they weren't planning releasing nor backporting our fixes. 
We tried to contribute changes to upstream, but it might be we have something extra on our fork that isn't pushed to upstream.

Most fixes we sent out were about data races and memory consumption. Becuase rclone is usually used as CLI, they didn't care much about memory consumption because the memory was trashed after CLI finished, but we are running as an agent, and Scylla consumes 95% of available memory on the machine, so we had to care. 
In my view, every rebase on top of upstream, must be followed with memory consumption testing for all supported platforms (Azure, GCP, AWS) because of experience we had.

**Comment by mykaul** [comment]
Looking at their recent release notes, seem like they have fixed some of the memory consumption issues:
https://github.com/rclone/rclone/commit/0c56c46523b1fea148ac732d29a30d576188621b
https://github.com/rclone/rclone/commit/a9bd0c8de6e74460ab990269e1f96834889304d2
and perhaps others I did not look further down.

**Comment by karol-kokoszka** [comment]
In short.
These are commits and changes that we applied to fork, but are not accepted/proposed to upstream
https://github.com/rclone/rclone/compare/master...scylladb:rclone:v1.54.0-patched

Let me go through all the commits and discussions.
22 is not so much.

**Comment by karol-kokoszka** [comment]
I will use following doc to track conclusions about comparison between rclone fork and rclone upstream.
https://docs.google.com/document/d/16yLgXHDGyuCzp1tSHFoP_TpBHNqr7TDihtIVpjTQ1uc/edit?usp=sharing

**Comment by karol-kokoszka** [comment]
RClone is supposed to be (and it is) a stable CLI tool allowing to sync data between a lot of different storages (https://rclone.org/overview).
But in scylla-manager we just explicitly define only 3 providers AWS, Azure and GCP. https://github.com/scylladb/scylla-manager/blob/0c742f50dd607877e1b047fe63eb3c3c7da72286/pkg/rclone/providers.go#L46-L97

The fork, together with the https://github.com/scylladb/scylla-manager/tree/master/pkg/rclone is trying to make it work as the HTTP server.
Couple of commits that are crucial for the manager to work are not accepted to the rclone upstream.
Commit that Scylla proposed to https://github.com/googleapis/google-api-go-client is not accepted by the maintainers and we ended up with the fork https://github.com/scylladb/google-api-go-client/.

One of the reasons to use RClone was the support for resumable uploads. Having the scenario where the file that is being transferred is pretty big,
we want to avoid the situation where the transfer is cancelled due to the longer network outage, and must be started from the beginning.
Rclone is not solving this problem. The only outage it can survive depends on the connection timeout set on the HTTP client.

RClone issue (in OPEN state) about resumable uploads https://github.com/rclone/rclone/issues/87
RClone issue (in OPEN state) about resumable uploads in GCP https://github.com/rclone/rclone/issues/4794

It's hard to maintain these forks even if it just means to keep it up to date with the upstream.

My first thought was that it's worth to get rid of forks and start using upstream RClone which is impossible (maybe this is too big statement) or just requires much effort.

Now, I think it's worth to get rid of RClone and move to the AWS, GCP, Azure SDKs directly.

@mykaul I'm closing this issue as won't fix, we have another one created by @dkropachev -> https://github.com/scylladb/scylla-manager/issues/3443 . The latter includes to check the effort needed to replace RClone with SDK. I'm gonna check this effort by including, feature flag guarded, possibility of making backup/restore with google SDK.

**Comment by Michal-Leszczynski** [comment]
This could actually help with https://github.com/scylladb/scylla-manager/issues/4162
