### ISSUE TITLE
scylla backups not working with blob storage

### ISSUE THREAD

**Issue by nidhirpatil** [scylladb/scylla-manager#3302]
I am trying to setup azure blob storage for scylla backups, according to the config file given here, i am adding ```
azure:
  account: <storage-name>
``` 
https://manager.docs.scylladb.com/stable/config/scylla-manager-agent-config.html 
but when i try to test this, getting this error, 
FAILED: yaml: unmarshal errors:
  line 2: field azure not found in type main.config

validated that the yaml file is added, can someone help with this issue, main.config seems to be coming from scylla manager code

*Installation details*
Scylla version (or git commit hash): 4.6.8-0.20220919.0aa9a8c26
Cluster size: 2 nodes with 65GB data each
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

**Comment by Michal-Leszczynski** [comment]
Hi, could you specify which version of Scylla Manager are you using?

**Comment by nidhirpatil** [comment]
i am using 3.0 
`Client version: 3.0.2-0.20221128.23e30739
Server version: 3.0.2-0.20221128.23e30739`

**Comment by Michal-Leszczynski** [comment]
I cannot replicate this error with SM 3.0.

Are you sure about the Scylla Manager version? Support for Azure is present since SM 2.4, so trying to start SM 2.3 agent  with config changes that you applied results in exactly the same error as you pasted here.
Moreover, newer versions of SM don't have `main.config`, but rather `agent.config` or `server.config`.

If you are sure about using SM 3.0, could you paste the whole SM and agent logs?
