### ISSUE TITLE
Default snapshot age is too low

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3309]
We set 12h as a default expirity time for snapshot.
After 12h, whenever backup task is resumed, it will take another snapshot. delete the old one and it will start the upload from scratch.
These issues #3298 , #3308 shows that upload of huge backup (5TB) may take much longer than 12h.

Default value of `age_max` should be extended to the higher value.

**Comment by Michal-Leszczynski** [comment]
The `age_max` config options matters only when resuming backup task.
If we start a backup task that takes 24h and we don't stop its execution in the meantime (nor it encounters an error), it should end regardless of the `age_max` config option.

Maybe it would be easier to see `age_max` as an additional config option that can be enabled by the user, but is disabled by default (like in repair task)? Setting it to some big value by default should usually generate the same results as not setting it at all.

In terms of mentioned issues, it's worth to note that in case agent crashes (even with increased `age_max` value), the next backup run would have to be started from the scratch, because at the beginning of backup run we validate that all hosts used in previous run are still alive:
https://github.com/scylladb/scylla-manager/blob/e629bbbf2b797ee3ad014d5ab0139632a73624fd/pkg/service/backup/service.go#L723-L739

**Comment by karol-kokoszka** [comment]
> Maybe it would be easier to see age_max as an additional config option that can be enabled by the user, but is disabled by default (like in repair task)? Setting it to some big value by default should usually generate the same results as not setting it at all.

It makes sense. The same config for repair is set to 0.
0 seems to be the safest option. I see no reason why it's set to 12h.

In cloud, we backup every 24h.




OK, I checked scylla-cloud and we schedule every 24h backup on the clusters.
I'll change the default max_age to 24h.

**Comment by karol-kokoszka** [comment]
The default supposed to be 24h.
https://github.com/scylladb/scylla-manager-enterprise/issues/1105

But was set to 12h in the PR closing the issue.
https://github.com/scylladb/scylla-manager-enterprise/pull/1152/files#

**Comment by karol-kokoszka** [comment]
OK, I'm changing it to 24h, not 0. 
As it was originally planned.
