### ISSUE TITLE
SM 3.1: `1680224216165_manager_restore_tests.py::TestScyllaMgmtRestore::test_restore_different_dc` regression

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3342]
https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/manager-dtest/22/testReport/junit/manager_restore_tests/TestScyllaMgmtRestore/test_restore_different_dc/

artifacts:
https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/manager-dtest/22/artifact/scylla-dtest/logs/1680224216165_manager_restore_tests.py%3A%3ATestScyllaMgmtRestore%3A%3Atest_restore_different_dc/
https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/manager-dtest/22/artifact/scylla-dtest/logs/1680224220424_manager_restore_tests.py%3A%3ATestScyllaMgmtRestore%3A%3Atest_restore_different_dc/

**Comment by Michal-Leszczynski** [comment]
I believe that this problem i caused by:
```
for node in first_dc_nodes:
    node.nodetool("drain")
self.restore_and_verify(mgr_cluster, backup_task, second_dc_nodes[0])
```
I t seems like after `nodetool drain` given node cannot issue load and stream. This fact is not validated while initializing nodes that will be used for restore purposes - we only validate agent's location access at this step.

Anyways, this kind of validation should be added in order to avoid this problem.
