### ISSUE TITLE
Automate materialized views and secondary indexes restoration 

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3370]
Current procedure of cluster restore requires end user to drop Materialized Views and Secondary Indexes after schema restoration and to recreate both after the repair.

We should automate it and make it to be a part of restore procedure supported by scylla manager.
To do so:
- before table restoration, scylla-manager must check `system_schema.views` table against any existing views. 
- scylla-manager must save materialized views and secondary indexes definitions in cache + place information about them in `progress` command output of restore task
- after the whole restore procedure, materialized views and secondary indexes must be recreated

**Comment by Michal-Leszczynski** [comment]
Let's examine it in the context of restore procedure:

1. Restore schema:
We allow only for full schema restoration, so MV and SI are always restored, but without their contents - but that's good since the base tables are also empty after this step. So hopefully they are in a correct state (it would be good to ensure that not restoring `system.*` tables does not have an impact on that)

2. Restore tables:
After restoring data to the base table and repairing both base table and the view, the view should also be in a correct state, because it acknowledged the new data in the base table (local experiments confirm that). Here we should forbid restoring MV and SI without restoring base table.

So why actually do we want to recreate the MV and SI? Is it because performance reasons (dropping and creating MV is faster than repairing empty MV)?

@karol-kokoszka
