### ISSUE TITLE
Restore Tasks error due to permissions when they are present

### ISSUE THREAD

**Issue by karlpvoss** [scylladb/scylla-manager#3403]
When creating and running a restore task on a cluster added to the Manager with `--username` and `--password` information present, the created task errors due to missing `ALTER` permissions, even when they are present.

Of note, the error is present for the `meta_migrations` table in both tests.

### Versions

```
sctool version
Client version: 3.1.0-0.20230424.6181fb96
Server version: 3.1.0-0.20230424.6181fb96

yum list installed | grep scylla
scylla.aarch64                      5.1.7-0.20230312.5c5a9633eab8  @scylladb-5.1
scylla-conf.aarch64                 5.1.7-0.20230312.5c5a9633eab8  @scylladb-5.1
scylla-jmx.noarch                   5.1.7-0.20230312.5c5a9633eab8  @scylladb-5.1-noarch
scylla-kernel-conf.aarch64          5.1.7-0.20230312.5c5a9633eab8  @scylladb-5.1
scylla-manager-agent.aarch64        3.1.0~0.20230424.6181fb96-1    @scylladb-manager-3.1
scylla-node-exporter.aarch64        5.1.7-0.20230312.5c5a9633eab8  @scylladb-5.1
scylla-python3.aarch64              5.1.9-0.20230423.ba1a57bd5531  @scylladb-5.1
scylla-server.aarch64               5.1.7-0.20230312.5c5a9633eab8  @scylladb-5.1
scylla-tools.noarch                 5.1.7-0.20230312.5c5a9633eab8  @scylladb-5.1-noarch
scylla-tools-core.noarch            5.1.7-0.20230312.5c5a9633eab8  @scylladb-5.1-noarch
```

### Task created via curl

```
# Trigger a table restore
curl "$MANAGER_ENDPOINT/cluster/$CLUSTER_ID/tasks" \
    -H 'Content-Type: application/json; charset=utf-8' \
    --data-binary @- << EOF
{
    "name": "restore-tables",
    "type": "restore",
    "enabled": true,
    "properties": {
        "location": ["s3:$BACKUP_LOCATION"],
        "snapshot_tag": "$SNAPSHOT_ID",
        "restore_tables": true
    }
}
```

Error:
```
sctool -c au-test progress restore/restore-tables
Run:            1cb64389-ff53-11ed-a2ed-021a5dccdb76
Status:         ERROR
Cause:          restore data: disable gc_grace_seconds: User manager has no ALTER permission on <table $KEYSPACE.meta_migrations> or any of its parents
Start time:     31 May 23 01:33:14 UTC
End time:       31 May 23 01:33:17 UTC
Duration:       2s
Progress:       0% | 0%
Snapshot Tag:   sm_20230531003002UTC
```

### Task created via `sctool`

```
sctool -c au-test restore --restore-tables -L s3:$BACKUP_LOCATION --snapshot-tag sm_20230531003002UTC
restore/29a6aad9-b15f-4c01-962e-9fba2df0aa05
```

Error:

```
sctool -c au-test progress restore/29a6aad9-b15f-4c01-962e-9fba2df0aa05
Run:            e580bfee-ff53-11ed-a2ee-021a5dccdb76
Status:         ERROR
Cause:          restore data: disable gc_grace_seconds: User manager has no ALTER permission on <table $KEYSPACE.meta_migrations> or any of its parents
Start time:     31 May 23 01:38:51 UTC
End time:       31 May 23 01:38:59 UTC
Duration:       7s
Progress:       0% | 0%
Snapshot Tag:   sm_20230531003002UTC
```

### Permissions

```
cqlsh -u manager -p '$MANAGER_PASSWORD' $TARGET_NODE_IP
Connected to $CLUSTER_NAME at $TARGET_NODE_IP:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
manager@cqlsh> LIST ALL PERMISSIONS OF manager;

 role    | username | resource        | permission
---------+----------+-----------------+------------
 manager |  manager | <all keyspaces> |      ALTER

(1 rows)
```

**Comment by karlpvoss** [comment]
Further testing shows that the manager role can directly make the changes stated without issue, but the error persists:

```
manager@cqlsh> ALTER TABLE module_on_hold.meta_migrations with gc_grace_seconds = 864002;
manager@cqlsh> DESCRIBE TABLE module_on_hold.meta_migrations;

CREATE TABLE module_on_hold.meta_migrations (
    version text PRIMARY KEY,
    applied timestamp
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864002
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

manager@cqlsh> LIST ALL OF manager;

 role    | username | resource        | permission
---------+----------+-----------------+------------
 manager |  manager | <all keyspaces> |      ALTER

(1 rows)
```

**Comment by karol-kokoszka** [comment]
@karlpvoss Thanks for reporting the issue.

ALTER permission on keyspaces you want to restore is actually the only requirement for the scylla user.

So, that should be enough:
```
manager@cqlsh> LIST ALL OF manager;

 role    | username | resource        | permission
---------+----------+-----------------+------------
 manager |  manager | <all keyspaces> |      ALTER

(1 rows)
```

I tried to reproduce the problem you have, but I failed miserably.
What I did:
- created user manager on the destination cluster `CREATE USER manager WITH PASSWORD 'test';`
- granted the user ALTER permissions on all keyspaces (to have the same permissions on manager user as you have)
- added the cluster to the manager `sctool cluster add --host <> --auth-token <> --username manager --password test`
- restored the schema `sctool restore -c <> -L <> -T <> --restore-schema`
- did a rolling restart of all cluster nodes
- restored the tables `sctool restore -c <> -L <> -T <> --restore-tables`

it succeeded.

I got the same error as you only when ALTER permission is missing on manager user.

What is interesting in the issue you reported is the fact that scylla-manager informs that manager user doesn't have a permission, but CQLSH lets this user to ALTER the table.

So here comes a question. Is it a multi-dc cluster ?
I'm asking about that, because I did another test with 2 datacenters.
Having nodes in DC1 and in DC2, I created the manager user in DC1 first.
`system_auth` was replicated in DC1 only.
I updated `system_auth` replication to include DC2 as well.

Afterwards:
- on DC1 I got 
`alter table <>.<> with tombstone_gc = {'mode': 'disabled'};` -> OK
- on DC2 I got
`Unauthorized: Error from server: code=2100 [Unauthorized] message="User manager has no ALTER permission on <table backuptest_restore.test_table> or any of its parents"`

It's somehow near to what you've got, but not from scylla-manager directly.

Last questions:
- what scylla version are you using ?
- can I see the output of `sctool status -c <your_cluster>` ?

**Comment by karlpvoss** [comment]
Hey @karol-kokoszka 

I appreciate the effort in trying to replicate my issues. What you're doing seems very close to what I'm doing.

Your mention of the `system_auth` keyspace got me thinking and I double checked; I was doing the `nodetool repair -pr system_auth` _before_ modifying the keyspace. Essentially doing:

1. `nodetool repair -pr system_auth`
2. `ALTER ROLE cassandra WITH PASSWORD = '{{ auth_secret.database_password }}';`
3. `CREATE ROLE IF NOT EXISTS manager WITH PASSWORD = '{{ manager_auth_secret.database_password }}' AND LOGIN = true;`
4. `GRANT ALTER ON ALL KEYSPACES TO manager;`
5. `ALTER KEYSPACE system_auth WITH REPLICATION = {'class' : 'NetworkTopologyStrategy', 'ap-southeast-2' : 3}`

Which is wrong. I have rectified this, moving `#1` down to `#5`, doing the keyspace repair after the changes.

This appears to have rectified the issue with failing due to permissions, but now I have one related to CDC: `Cannot ALTER <table system_distributed.cdc_generation_descriptions>`. I understand that this is currently not supported by scylla manager, but it looks like i should be able to opt out of them using the `--keyspace` flag and the `!` operator.

Just so all the information is here:
- This is a single-dc cluster
- Scylla versions are at the top of the issue
- `sctool status`:
```
sctool -c au-test status
Datacenter: ap-southeast-2
╭────┬───────────┬──────────┬────────────────┬────────┬──────┬─────────┬────────┬───────┬──────────────────────────────────────╮
│    │ CQL       │ REST     │ Address        │ Uptime │ CPUs │ Memory  │ Scylla │ Agent │ Host ID                              │
├────┼───────────┼──────────┼────────────────┼────────┼──────┼─────────┼────────┼───────┼──────────────────────────────────────┤
│ UN │ UP (12ms) │ UP (1ms) │ 10.100.143.136 │ 57m44s │ 4    │ 15.250G │ 5.1.7  │ 3.1.0 │ 70e30582-b6aa-453d-8643-68f04cc949aa │
│ UN │ UP (6ms)  │ UP (0ms) │ 10.100.62.84   │ 59m20s │ 4    │ 15.250G │ 5.1.7  │ 3.1.0 │ c367834a-952e-416b-ae37-cee7678c949d │
│ UN │ UP (10ms) │ UP (1ms) │ 10.100.71.35   │ 58m48s │ 4    │ 15.250G │ 5.1.7  │ 3.1.0 │ 6503017e-4380-4e53-8e1b-ae2a33f6e8c8 │
╰────┴───────────┴──────────┴────────────────┴────────┴──────┴─────────┴────────┴───────┴──────────────────────────────────────╯
```
