### ISSUE TITLE
Deprecate the <0,1> intensity flag support

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3424]
https://manager.docs.scylladb.com/stable/sctool/repair.html#intensity

`--intensity`
   - 0: Set number of token ranges per repair job automatically.
   - 1, 2, 3, 4, .... : Specify number of ranges per repair job manually.
   - **(0,1): The decimal (0,1) value support in --intensity should be deprecated. Allow the user to specify, but ignore it, setting to 1 internally.**

The --intensity option controls how many token ranges a repair job repairs.

For example, a node owns 512 token ranges, max_repair_ranges_in_parallel is 6.

Setting --intensity to 1, 1 token ranges will be sent to Scylla core per repair job.

Setting --intensity to 2, 2 token ranges will be sent to Scylla core per repair job.

Setting --intensity to 6, 6 token ranges will be sent to Scylla core per repair job.

TODO:
- Update the repair service and remove all the logic connected with (0,1) float intensity level
- Update the documentation https://manager.docs.scylladb.com/stable/sctool/repair.html#intensity

**Comment by vladzcloudius** [comment]
@karol-kokoszka could you, please, clarify what's the point of this change?

**Comment by Michal-Leszczynski** [comment]
We asked @asias about repair and what would be the best way for SM to orchestrate it.
It turned out that shard count shouldn't be taken into consideration when calculating the amount of token ranges repaired by Scylla in a single job (although it should be used for choosing the repair master).

Intensity lesser than 1 is defined as:
`It can be a decimal between (0,1), in that case it specifies percent of shards that can be repaired in parallel on a repair master node.`
So that's why we wanted to deprecate it.

On the other hand, it was also said that:
> From Asias: There is no limitation of sending how many token ranges per repair job. Sending less than max_repair_ranges_in_parallel per repair job allows users to run repair less aggressively, which is the main reason we want to introduce the option in the first place. We could just send max_repair_ranges_in_parallel per repair job, but this means we will send a lot of repair jobs if there are too many token ranges per node. I think it makes more sense to send some percentage of token ranges per repair job, say 5% of the total token ranges we need to repair per repair job. This works for all cases no matter how many token ranges a node owns. Internally, scylla will cap the number of ranges to repair in parallel anyway. Sending more token ranges per repair job than  max_repair_ranges_in_parallel will not have performance impact. It only has an impact on the fail and resume granularity. 

So maybe we could change the meaning of intensity to represent the % of all token ranges sent in one repair job?
However, even slight changes to flag definition could lead to unexpected errors on the user side.

@karol-kokoszka

**Comment by vladzcloudius** [comment]
> We asked @asias about repair and what would be the best way for SM to orchestrate it. It turned out that shard count shouldn't be taken into consideration when calculating the amount of token ranges repaired by Scylla in a single job

Correct. This is true since we moved away from sending per-shard ranges to sending VNODE ranges (which involve all shards).

> (although it should be used for choosing the repair master).

Are you referring the "mixed cluster heuristics"? 

> 
> Intensity lesser than 1 is defined as: `It can be a decimal between (0,1), in that case it specifies percent of shards that can be repaired in parallel on a repair master node.` So that's why we wanted to deprecate it.

I see. Maybe it indeed makes sense to deprecate it since there is no per-shard repair task anymore.

> 
> On the other hand, it was also said that:
> 
> > From Asias: There is no limitation of sending how many token ranges per repair job. 
> Sending less than max_repair_ranges_in_parallel per repair job allows users to run repair less aggressively, which is the main reason we want to introduce the option in the first place. We could just send max_repair_ranges_in_parallel per repair job, but this means we will send a lot of repair jobs if there are too many token ranges per node. I think it makes more sense to send some percentage of token ranges per repair job, say 5% of the total token ranges we need to repair per repair job. This works for all cases no matter how many token ranges a node owns. Internally, scylla will cap the number of ranges to repair in parallel anyway. Sending more token ranges per repair job than  max_repair_ranges_in_parallel will not have performance impact. It only has an impact on the fail and resume granularity.

There must have been some (probably unrelated) context for this quote because we really don't want SM to do what is described above. At least because it clearly contradicts what's written here: https://manager.docs.scylladb.com/stable/sctool/repair.html#parallel
And we really like the definition of what's written in the page above as I've mentioned 
here https://github.com/scylladb/scylla-manager/issues/3425#issuecomment-1636511703

We want SM to strictly comply to the `--parallel` definition of a specific job.

> 
> So maybe we could change the meaning of intensity to represent the % of all token ranges sent in one repair job? However, even slight changes to flag definition could lead to unexpected errors on the user side.
> 
> @karol-kokoszka

I think we can simply deprecated it after we fix https://github.com/scylladb/scylla-manager/issues/3463

**Comment by Michal-Leszczynski** [comment]
Right now the general idea is to have two flags:
- `parallel` - defines total number of repair jobs in the cluster that can be run in parallel
- `single-host-parallelism` - defines total number of repair jobs that can be run in parallel on a single host

So the meaning of `parallel` is going to be preserved.
The second flag (with default value 1) would be used in case user wants to repair faster.

**Comment by vladzcloudius** [comment]
> Right now the general idea is to have two flags:
> 
>     * `parallel` - defines total number of repair jobs in the cluster that can be run in parallel
> 
>     * `single-host-parallelism` - defines total number of repair jobs that can be run in parallel on a single host
> 
> 
> So the meaning of `parallel` is going to be preserved. The second flag (with default value 1) would be used in case user wants to repair faster.

I'm confused. This makes little sense to me.
What's the point of having a second parameter if you can simply use a `--parallel N` with N greater than a number of total number of nodes to achieve the same?

Having a single parameter would avoid following confusing situations:

Example 1
* parallel: 1
* single-host-parallelism: 7

Example 2:
* parallel: 7
* single-host-parallelism: 6

And on top of that, there is no sense in changing the currently documented restriction: a single node can participate in up to a **single** repair task.

What you want to control in addition to that is the number of **token ranges** that single task can repair in parallel (on the same replica set of course).

And probably, instead of introducing yet-another parameter you can simply use the already existing `intensity` parameter. And instead of deprecating it simply don't allow it to go below 1 - the rest of its definition remains exactly the same: "number of token ranges that can be repaired on a single shard."

Please, let me know if this makes sense?

**Comment by asias** [comment]
Hello guys, This is what I wrote in the new repair doc a few weeks ago. I even gave detailed and concrete examples. I think we do not need the new option --single-host-parallelism. The --intensity option is good enough for the purpose of controlling the ranges in parallelism per job. 


```
Here are my thoughts about the two options:

1) --intensity
   0: Set number of token ranges per repair job automatically.
   1, 2, 3, 4, .... : Specify number of ranges per repair job manually.
   (0,1): The decimal (0,1) value support in --intensity should be deprecated. Allow the user to specify, but ignore it, setting to 1 internally.


The --intensity option controls how many token ranges a repair job repairs.

For example, a node owns 512 token ranges, max_repair_ranges_in_parallel is 6.

Setting --intensity to 1, 1 token ranges will be sent to Scylla core per repair job.

Setting --intensity to 2, 2 token ranges will be sent to Scylla core per repair job.

Setting --intensity to 6, 6 token ranges will be sent to Scylla core per repair job.

Setting --intensity to 7, 7 token ranges will be sent to Scylla core per repair
job, but only 6 token ranges will be repaired at the same time.

Setting numbers smaller than max_repair_ranges_in_parallel allows users to run repairs less aggressively by controlling token ranges scheduling.


2) --parallel
   0: Set to NR_NODDES / RF automatically
   [1,2,3 ... NR_NODDES / RF]: Set max number of jobs that can run at the same time in the cluster.


The --parallel option controls how many repair jobs scylla manager starts in
the cluster at the same time.

For example, 6 nodes in the cluster (n1, n2, n3, n4, n5, n6), RF = 2.

Setting --parallel to 1, at any point in time, 1 repair job can be run.
t1: job 1 repairs n1 and n2
t2: job 2 repairs n1 and n3
t3: job 3 repairs n1 and n4
t4: job 4 repairs n1 and n5
...
tn: job n repairs n5 and n6

Setting --parallel to 2, at any point in time, 2 repair jobs can be run.
t1: job 1 repair n1 and n2, job 2 repairs n3 and n4
t2: job 3 repair n1 and n2, job 4 repairs n5 and n6

Setting --parallel to 3, at any point in time, 3 repair jobs can be run.
t1: job 1 repair n1 and n2, job 2 repairs n3 and n4, job 3 repairs n5 and n6.
t2: job 4 repair n1 and n2, job 5 repairs n3 and n4, job 6 repairs n5 and n6.

Setting values to larger than NR_NODDES / RF, --parallel will be capped to NR_NODDES / RF.
Setting value to zero, --parallel will be set to NR_NODDES / RF.

Setting a value less than NR_NODDES / RF means some of the nodes in the cluster are
not participating in repair at some point in time.

Setting numbers smaller than NR_NODDES / RF allows users to run repairs less aggressively by controlling repair jobs scheduling.

Notes: by default, we set --intensity and --parallel to 0, to use automatic token ranges and repair job setting.
```

**Comment by Michal-Leszczynski** [comment]
> There is no sense in changing the currently documented restriction: a single node can participate in up to a single repair task.
Which means - why do we even need this new parameter to begin with?

This flag would allow to run repair faster.
SM 3.1.3 patch release will ensure that there is only one repair job per host at a time by introducing `--single-host-parallelism`. Single repair job per host will be ensured by setting this flag to 1, while the default value is 0 (for now), which basically fall backs to the previous behavior (the one that does not follow docs). 
The reason to leave the default behavior as it is for now, is that this change requires more testing in terms of performance. It was observed by @dkropachev, that setting `--single-host-parallelism 1` (with the same intensity) makes SCT repair tests run for twice as much time and we don't want to have negative influence on clusters where repair was running fine.

Getting rid of this flag by simply increasing the intensity won't really work, because:
> Internally, scylla will cap the number of ranges to repair in parallel anyway. Sending more token ranges per repair job than max_repair_ranges_in_parallel will not have performance impact. It only has an impact on the fail and resume granularity.

So setting intensity greater than `max_repair_ranges_in_parallel` doesn't really bring any real benefit.

> And instead of deprecating it simply don't allow it to go below 1 - the rest of its definition remains exactly the same: "number of token ranges that can be repaired on a single shard."

We are trying to remove (mostly) shard count from repair logic, so intensity will be just "the amount of token ranges repaired in a single job".

Another approach could be not to use `--single-host-parallelism` and instead calculate it internally:
```
single-host-parallelism = max_repair_ranges_in_parallel / intensity
```
And just send `min(max_repair_ranges_in_parallel, intensity)` ranges per job, but that's a little bit more tricky and could create problems when used inappropriately.

**Comment by Michal-Leszczynski** [comment]
> I think we do not need the new option --single-host-parallelism. 

So repairing faster than one job per host with `max_repair_ranges_in_parallel` ranges isn't really needed by anyone? I though that it might be useful to sometimes run 2 or 3 of repair jobs in parallel on a single host, so that the repair runs faster (e.g. when cluster has a maintenance window).

**Comment by asias** [comment]
> > I think we do not need the new option --single-host-parallelism.
> 
> So repairing faster than one job per host with `max_repair_ranges_in_parallel` ranges isn't really needed by anyone? I though that it might be useful to sometimes run 2 or 3 of repair jobs in parallel on a single host, so that the repair runs faster (e.g. when cluster has a maintenance window).

A single repair job (started by a restful request) with max_repair_ranges_in_parallel is going to generate enough workload. 

Even if we want to run more than one repair job per host, we can use the --parallel option,  allowing --parallel > NR_NODES / RF,   e.g., 2* (NR_NODDES / RF) will run 2 repair jobs at most.

This matches with --parallel < NR_NODES / RF, which allows less than 1 repair job per host (average).

**Comment by Michal-Leszczynski** [comment]
> Even if we want to run more than one repair job per host, we can use the --parallel option, allowing --parallel > NR_NODES / RF, e.g., 2* (NR_NODDES / RF) will run 2 repair jobs at most.

This is a little bit problematic, because one Scylla Manager repair task can specify multiple keyspaces with different RFs. That is also why I don't really think that the current definition of `--parallel` is that easy to use. 

Let's say we have a cluster with 2 dcs, 6 nodes each. We want to repair two keyspaces with the following replications:
```
{'class': 'NetworkTopologyStrategy', 'dc1': 3, 'dc2': 3}
{'class': 'NetworkTopologyStrategy', 'dc1': 1, 'dc2': 1}
```
One repair job in keyspace with RF=6 doesn't impact the cluster at the same level as one repair job in keyspace with RF=2, yet the `--parallel` flag should be respected in the same way in both of them. So setting `--parallel 2` would mean that all 12 nodes can take part in repairing the first keyspace at a time, while only 4 nodes can take part in repairing the second keyspace at a time.

So allowing for:
```
--parallel > NR_NODES / RF
```
could create some unexpected results when repairing multiple keyspaces.

On the other hand, having something like `--single-host-parallelism` could allow us to put even amount of pressure on every node despite different values of currently repaired keyspace RF.
