### ISSUE TITLE
Scylla manager fails to backup custom UDA

### ISSUE THREAD

**Issue by SliverFang** [scylladb/scylla-manager#3433]
Creating backup using scylla manager fails with the error

```await schema: get schema: cql keyspace traffickeyspace metadata: template: aggregate:4:11: executing "aggregate" at <ne $i 0>: error calling ne: incompatible types for comparison```

We had a UDA in our keyspace, when we dropped it and retried getting the backup, it was successful. The UDA has the following schema
```
CREATE AGGREGATE ks.average(double)
SFUNC avgstate STYPE tuple<int, double>
FINALFUNC avgfinal
INITCOND (0,0.0);

CREATE FUNCTION ks.avgfinal(
  state tuple<int, double>)
CALLED ON NULL INPUT
RETURNS double
LANGUAGE lua
as $$
    r=0
    r=state[2]
    r=r/state[1]
    return r
    $$;

CREATE FUNCTION ks.avgstate(
  state tuple<int, double>,
  val double)
CALLED ON NULL INPUT
RETURNS frozen<tuple<int, double>>
LANGUAGE lua
AS $$
  return { state[1]+1, state[2]+val }
  $$;
```

The aggregate function works as expected, only encountering the error while taking backup using syclla manager.

Scylla Manager Version : 3.1
Scylla DB Version : 5.2

**Comment by Michal-Leszczynski** [comment]
Thank you for reporting!
This looks like a bug in gocql, so I created corresponding issue in their repository.

There are two things about backing up schema in a form of cql file:
- it's done for historical reasons, SM does not use this file in the restore process (it uses backed-up schema SSTables, which are always included in the backup)
- it's not performed when SM does not have the cql credentials to the cluster

So until this gets fixed, a workaround could be to just take away the cql credentials from SM, so that it does not try to backup schema in form of a cql file, which causes this error. This can be done simply by running:
```
sctool cluster update -c CLUSTER_ID --delete-cql-credentials
```

**Comment by tzach** [comment]
@Michal-Leszczynski please add a link to the gocql issue

**Comment by Michal-Leszczynski** [comment]
https://github.com/scylladb/gocql/issues/130

**Comment by shantanugithub** [comment]
@Michal-Leszczynski Even after deleting the cql credentials, we are getting the same error. Please help resolving this -

![Screenshot 2023-06-26 at 2 18 01 PM](https://github.com/scylladb/scylla-manager/assets/7384987/88b9ce58-3611-4ea6-a429-aefa422f612a)
![Screenshot 2023-06-26 at 2 18 27 PM](https://github.com/scylladb/scylla-manager/assets/7384987/aee42c70-319e-4208-87fb-ad3d4129bbcf)
![Screenshot 2023-06-26 at 2 19 40 PM](https://github.com/scylladb/scylla-manager/assets/7384987/bce93b7a-8a45-4f5c-ac16-9cbf480cb397)

**Comment by Michal-Leszczynski** [comment]
Is your cluster cql password protected?
If not, deleting cql credentials indeed wouldn't solve this issue, because they are not used in the first place. In terms of a temporary workaround, enabling cql password authorization is the only thing that comes to my mind. 

Nevertheless, even though it is a gocql bug, SM shouldn't stop backup process because of this kind of errors, so we need to change that.

**Comment by shantanugithub** [comment]
Thanks @Michal-Leszczynski . It worked after enabling the Authentication and Authorization :)
