### ISSUE TITLE
Re-consider repair to MV tables

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-manager#3530]
Based on feedback from the core developers, need to decide if we do wish to repair MV tables or skip.

**Comment by Michal-Leszczynski** [comment]
So there should be a new flag added so that this can be configurable.
Is there any link to this feedback so that we can see all important information here?

**Comment by nyh** [comment]
Good question. In the past there were some theoretical arguments why repairing the view can cause "ghost rows" - rows corresponding to values that never successfully reached the base table but appear in the view - to become permanent. However, I now think that there are better arguments why repairing the view is important for the same benign reasons that repairing any table is important: preventing of resurrected data after gc_grace_seconds and getting up-to-date results from CL=1 reads. So I think we should do the view repair.

I think it's a good idea what you do in Scylla Manager (which I wasn't aware of, by the way!) to do the base repair first, and only then the view repair, because if there is mismatching data in the base table, this more-or-less guarantees mismatching data in the view table, and we  should let the base-table repair (which also sends view updates) try to fix both first, and only then fall back to trying to repair the view alone.

CC @cvybhu

**Comment by karol-kokoszka** [comment]
@mykaul Basing on the @nyh feedback, looks that we have nothing to do here.
Scylla manager 3.2 assures (when the credentials are provided) that base table is repaired before the view.

Do we want to have opt-out flag for views on the repair task ? I'm not sure if anyone will be using that if we keep repairing the views by default.
Views can be filtered out with this flag still https://manager.docs.scylladb.com/stable/sctool/repair.html#k-keyspace

**Comment by mykaul** [comment]
No, closing
