### ISSUE TITLE
Changed intensity/parallel values should be respected on retry.

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3580]
If intensity/parallelism values are changed for a running repair, a retry of a failure of that repair should inherit the parallelism/intensity altered settings until that run successfully completes or is started with --no-continue.

As per https://github.com/scylladb/scylla-enterprise/issues/3419

**Comment by Michal-Leszczynski** [comment]
Do we want change `sctool repair control` to also permanently change parallel/intensity for the next task runs, or only for the current run?

**Comment by karol-kokoszka** [comment]
We just want to make sure that the current task run is affected.
https://manager.docs.scylladb.com/stable/sctool/repair.html#reschedule-a-repair
The CLI above can be used to update the task permanently.

**Comment by Michal-Leszczynski** [comment]
My proposition:

Add `intensity` and `parallel` to `scylla_manager.repair_run`. This way we can prioritize params from DB (when we continue previous run) over standard params (used when running from scratch). This means that params set by `repair control` will be respected in all runs continuing the run when they were set (e.g. params will be respected when pausing/resuming task).

Side benefit of this solution is that we would be able to display effective `parallel` and `intensity` of a already finished task (right now we display those params only for currently running tasks, because we lack this info in DB).
