### ISSUE TITLE
Do we support incremental backup?

### ISSUE THREAD

**Issue by zey1996** [scylladb/scylla-manager#3624]
I have notice scylla support incremental backup. but I can't find it in scylla-manager.  
Do we support incremental backup? OR may be we can add it in sometime.

**Comment by Michal-Leszczynski** [comment]
Scylla Manager does not support incremental backup right now and I don't think that it is planned for near future
(cc @tzach).

Scylla Manager uses the full backup procedure (it creates snapshots of all tables and uploads them to remote location),
but because many snapshots of the same backup task might consist of the same, immutable SSTables, the files don't need to be uploaded with every backup. Example:
- time 1: table has SSTables:  A, B, C -> backup -> upload A, B, C to the remote location
- time 2: table has SSTables: A, B, C, D -> backup -> upload only D to the remote location
- time 3: table has SSTables: A, B, E -> backup -> upload only E to the remote location (even if E consists only of data compacted from C, D)

**Comment by tzach** [comment]
https://github.com/scylladb/scylladb/issues/214
