### ISSUE TITLE
Restore schema does not work when keyspace/table was deleted

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-manager#3677]
Steps to reproduce:
1. Create backup.
2. Delete table/keyspace
3. Restore backup.

Since `DROP ` op have higher timestamp it is going to override all the ops from the schema snapshot and you end up with the `keyspace/schema` still deleted.

If you run `restore --restore-tables` it is not going to work since table/keyspace is gone.

**Comment by karol-kokoszka** [comment]
This scenario is not and cannot be supported. Such a situation requires clean cluster without the schema changes history. 
It's clearly written in the docs https://manager.docs.scylladb.com/stable/restore/restore-tables.html

**Comment by karol-kokoszka** [comment]
But this is a bug describing current situation. 
Besides we write in the docs that table must be TRUNCATED not DROP.

The restore approach may be changed in future but I don't see this issue to be relevant for these future changes.
Please correct me if I'm wrong, but if the schema will be restored using CQL queries, then there will be no need to TRUNCATE instead of DROP.

**Comment by Michal-Leszczynski** [comment]
> Please correct me if I'm wrong, but if the schema will be restored using CQL queries, then there will be no need to TRUNCATE instead of DROP.

That's correct. Restoring schema via cql will allow SM to restore schema of DROPPED tables.
