### ISSUE TITLE
[SCT] Extend the backup test to verify that delta backup without new data added into DB takes -> 0 time

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#3936]
Tests the story https://github.com/scylladb/scylla-manager/issues/3827

The current backup test should be extended with one more check:
- delta backup without new data added into database takes -> 0 time

Pay attention that current behavior should be applied only for Scylla >= 2024.1 and Scylla Manager > 3.3.0.

**Comment by karol-kokoszka** [comment]
After checking the output of the last SCT run, it looks that the compaction must be disabled. Otherwise, new set of SSTables is created what ends up in the situation that almost no deduplication is applied at all.

![image](https://github.com/user-attachments/assets/95c371f8-e620-434a-98fe-6eb2439f0c85)

^^ running compaction

![image](https://github.com/user-attachments/assets/dbb9664c-faec-4f45-8098-57ef359bedf1)

^^ backup one after another

SCTool backup output

```
ubuntu@manager-restore-incremen-monitor-node-72c685dc-1:~$ sctool progress backup/daac7e1d-7de8-4f02-8187-5a5f32919939  -c mgr_cluster1
Run:		28b08f57-558a-11ef-a382-029e959780ad
Status:		DONE
Start time:	08 Aug 24 13:28:54 UTC
End time:	08 Aug 24 15:17:35 UTC
Duration:	1h48m40s
Progress:	100%
Snapshot Tag:	sm_20240808132855UTC
Datacenters:	
  - us-east

╭─────────────┬──────────┬──────────┬──────────┬──────────────┬────────╮
│ Host        │ Progress │     Size │  Success │ Deduplicated │ Failed │
├─────────────┼──────────┼──────────┼──────────┼──────────────┼────────┤
│ 10.12.0.126 │     100% │ 546.998G │ 546.998G │            0 │      0 │
│ 10.12.3.148 │     100% │ 536.459G │ 536.459G │            0 │      0 │
│ 10.12.3.247 │     100% │ 537.364G │ 537.364G │            0 │      0 │
╰─────────────┴──────────┴──────────┴──────────┴──────────────┴────────╯
ubuntu@manager-restore-incremen-monitor-node-72c685dc-1:~$ sctool progress backup/0c358ebb-8569-4122-8d64-ed3129650c81 -c mgr_cluster1
Run:		78fabcb6-5599-11ef-a383-029e959780ad
Status:		DONE
Start time:	08 Aug 24 15:18:31 UTC
End time:	08 Aug 24 16:56:35 UTC
Duration:	1h38m3s
Progress:	99%
Snapshot Tag:	sm_20240808151832UTC
Datacenters:	
  - us-east

╭─────────────┬──────────┬──────────┬──────────┬──────────────┬────────╮
│ Host        │ Progress │     Size │  Success │ Deduplicated │ Failed │
├─────────────┼──────────┼──────────┼──────────┼──────────────┼────────┤
│ 10.12.0.126 │      99% │ 539.823G │ 539.505G │            0 │      0 │
│ 10.12.3.148 │      99% │ 536.106G │ 536.003G │            0 │      0 │
│ 10.12.3.247 │      99% │ 527.481G │ 526.367G │            0 │      0 │
╰─────────────┴──────────┴──────────┴──────────┴──────────────┴────────╯
```

Content comparison of two manifest files created for these snapshots, showed that just 3 SSTables are duplicated. All the rest are unique.

Duplicated files: 27
Unique: 55,368

It happened due to compaction OFC.

The recommendation is to disable the compaction for the test run.

The sctool output discovered a bug in backup related to statistics, there is 0 deduplicated data, what is not true.
There is going to be another issue for that.
