### ISSUE TITLE
Make possible to restore backups created on latest Scylla versions (for example, 6.0) into clusters with older versions (for example, 5.4)

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#4038]
As per @Michal-Leszczynski [comment](https://github.com/scylladb/scylla-cluster-tests/issues/7318#issuecomment-2367591578), it's feasible and we are just missing the implementation for that.

**Comment by Michal-Leszczynski** [comment]
@mikliapko Actually, after some more thinking, I don't think we should support that.
The reason is that the newer Scylla version might contain some new system tables that weren't present in the older Scylla version. Restoring schema via sstables (so all of the schema - including system tables), wouldn't be safe here.
That's why we have a [warning in SM docs](https://manager.docs.scylladb.com/stable/restore/index.html) warning from restoring into older Scylla version.

**Comment by mikliapko** [comment]
> @mikliapko Actually, after some more thinking, I don't think we should support that. The reason is that the newer Scylla version might contain some new system tables that weren't present in the older Scylla version. Restoring schema via sstables (so all of the schema - including system tables), wouldn't be safe here. That's why we have a [warning in SM docs](https://manager.docs.scylladb.com/stable/restore/index.html) warning from restoring into older Scylla version.

Got it, alright, in such case closing the ticket as not valid.
